#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(2500);

	setMotorSpeed(leftMotor, 100);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, 0); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(1950);

}
