#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Medium, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{
	// Move forward at half power for 1.5 seconds
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motor1) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motor6) to half power forward (50)
	sleep(1500);			//Wait for 1.5 seconds before continuing on in the program.

	// Stop for 1 second
	setMotorSpeed(leftMotor, 0);	//Set the leftMotor (motor1) to Off
	setMotorSpeed(rightMotor, 0);  	//Set the rightMotor (motor6) to Off
	sleep(1000);			//Wait for 1 second before continuing on in the program.

	// Move reverse at half power for 1.5 seconds
	setMotorSpeed(leftMotor, -50);	//Set the leftMotor (motor1) to half power reverse (50)
	setMotorSpeed(rightMotor, -50);	//Set the rightMotor (motor6) to half power reverse (50)
	sleep(1500);			//Wait for 1.5 seconds before continuing on in the program.

	// Turn left at full power for 0.75 seconds
	setMotorSpeed(leftMotor, 100);	//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(rightMotor, -100);//Set the rightMotor (motor6) to full power reverse (-100)
	sleep(750);			//Wait for .75 second before continuing on in the program.
}
