#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(2000);

	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, -50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(390);

	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(2000);

	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, -50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(390);

	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(2000);

	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, -50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(390);

	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, 50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(2000);

	setMotorSpeed(leftMotor, 50);	//Set the leftMotor (motorC) to half power forward (50)
	setMotorSpeed(rightMotor, -50); 	//Set the rightMotor (motorB) to half power forward (50)
	sleep(390);

}
